### ISSUE TITLE
Live demo

### ISSUE THREAD

**Issue by rain1024** [anmolkoul/node-dc-mongo#1]
@anmolkoul : this project is awsome.

Can you provide a simple live demo for it?

**Comment by anmolkoul** [comment]
Sure.. I can share it via local tunnel. Would that be fine?

Sent from my Windows Phone

**Comment by rain1024** [comment]
@anmolkoul: Thanks for fast reply :+1: 

I think it would be a lot more interesting if you can put it online, and plug it in github.io

**Comment by anmolkoul** [comment]
Please forgive my ignorance here. But my limited hosting knowledge tells me that a node server can not be hosted on git.. Can you give me some pointers here?

Sent from my Windows Phone

**Comment by rain1024** [comment]
With mongodb, nodejs and some HTML, I think you can use [digitalocean](https://www.digitalocean.com/features/one-click-apps/mean/) for making it online. 

So you can have a nice demonstration for some guys who not familiar with nodejs things.

I wish to see it soon :heart_eyes:

**Comment by anmolkoul** [comment]
Sure.. Give me a day. :)

Sent from my Windows Phone

**Comment by anmolkoul** [comment]
d3 functionality is working at anmolkoul.github.io
Setting up a node server for demo is gonna take some time. Closing this issue until further notice :)
