### ISSUE TITLE
Cannot find your dataset

### ISSUE THREAD

**Issue by avnigulati** [anmolkoul/node-dc-mongo#7]
How do I access the dataset that you used? It gives 404 Error when I click on the link to your dropbox.

**Comment by ghost** [comment]
https://research.donorschoose.org/t/download-opendata/33

**Comment by s-h-x** [comment]
Note that from the link above, all URLs point to the full dataset :
http://s3.amazonaws.com/open_data/opendata_projects000.gz

Make sure you keep no more than 20000 lines from this file before you import it or your node server will run out of memory and fetching data will take a lot of time

Plus : make sure you add this header line :
`_projectid, _teacher_acctid, _schoolid, school_ncesid, school_latitude, school_longitude, school_city, school_state, school_zip, school_metro, school_district, school_county, school_charter, school_magnet, school_year_round, school_nlns, school_kipp, school_charter_ready_promise, teacher_prefix, teacher_teach_for_america, teacher_ny_teaching_fellow, primary_focus_subject, primary_focus_area ,secondary_focus_subject, secondary_focus_area, resource_type, poverty_level, grade_level, vendor_shipping_charges, sales_tax, payment_processing_charges, fulfillment_labor_materials, total_price_excluding_optional_support, total_price_including_optional_support, students_reached, total_donations, num_donors, eligible_double_your_impact_match, eligible_almost_home_match, funding_status, date_posted, date_completed, date_thank_you_packet_mailed, date_expiration
`

And it appears that the date format may have changed, I had to use in Dashboard.js :
`	var dateFormat = d3.time.format("%Y-%m-%d %H:%M:%S");`

**Comment by avnigulati** [comment]
Thanks for your response !
